DROP TABLE IF EXISTS `Volunteers`;
CREATE TABLE `Volunteers` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `open_id` varchar(2048) COLLATE utf8mb4_unicode_ci,
  `公司名字` varchar(500) COLLATE utf8mb4_unicode_ci,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `贵公司员工数量` INTEGER COLLATE utf8mb4_unicode_ci,
  `贵公司员工平均年龄约` INTEGER COLLATE utf8mb4_unicode_ci,
  `已成立组织` varchar(500) COLLATE utf8mb4_unicode_ci,
  `组织活动频次` varchar(500) COLLATE utf8mb4_unicode_ci,
  `组织什么活动` varchar(500) COLLATE utf8mb4_unicode_ci,
  `意向成立组织` varchar(500) COLLATE utf8mb4_unicode_ci,
  `了解组织要求` varchar(500) COLLATE utf8mb4_unicode_ci,
  `公司活动` varchar(500) COLLATE utf8mb4_unicode_ci,
  `其他公司活动` varchar(500) COLLATE utf8mb4_unicode_ci,
  `帮助成立组织` varchar(500) COLLATE utf8mb4_unicode_ci,
  `组织活动困难` varchar(500) COLLATE utf8mb4_unicode_ci,
  `其他组织活动困难` varchar(500) COLLATE utf8mb4_unicode_ci,
  `了解党群服务` varchar(500) COLLATE utf8mb4_unicode_ci,
  `联系人姓名` varchar(100) COLLATE utf8mb4_unicode_ci,
  `联系人电话` varchar(100) COLLATE utf8mb4_unicode_ci,
  `联系人职务` varchar(100) COLLATE utf8mb4_unicode_ci,
  `行业领域` varchar(100) COLLATE utf8mb4_unicode_ci,
  `期待和建议` varchar(2048) COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业调查问卷';
